version: '3'
services:
  nginx:
    build: .
    image: anadk/backend-demo
    container_name: backend
    networks:
      - backend-network
    ports:
      - "80:3000"
    environment:
      ENV_MODE: ${ENV_MODE}
networks:
  backend-network:
    driver: bridge