version: '3'
services:
  backend:
    build: .
    image: anadk/backend-demo
    container_name: backend
    networks:
      - demo-net
    ports:
      - "80:3000"
    environment:
      ENV_MODE: ${ENV_MODE}
networks:
  demo-net:
    name: demo-net